version: '2'
services:
  console:
    build:
      context: ./services/console
      dockerfile: Dockerfile
    volumes_from:
      - php
    tty: true
  web:
    image: nginx:1.11.1
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./services/nginx/config:/etc/nginx/conf.d
  php:
    build:
      context: ./services/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/mnt/app
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "123123"
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis:3.2.1
    ports:
      - "6379:6379"
volumes:
  db:
    driver: local
