version: '2'
services:
  console:
    build:
      context: ./services/console
      dockerfile: Dockerfile
    volumes_from:
      - php
    tty: true
  web:
    image: nginx:1.11.1
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes_from:
      - unison
    volumes:
      - ./services/nginx/config:/etc/nginx/conf.d
  php:
    build:
      context: ./services/php
      dockerfile: Dockerfile
    volumes_from:
      - unison
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "123123"
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis:3.2.1
    ports:
      - "6379:6379"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: "db"
      PMA_USER: "root"
      PMA_PASSWORD: "root"
  unison:
    image: onnimonni/unison:2.48.4
    environment:
      - UNISON_DIR=/mnt/app
    ports:
      - "5000:5000"
    volumes:
      - app:/mnt/app/
volumes:
  db:
    driver: local
  app:
    driver: local
